name: ladex
description: "pokedex app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity:
  rxdart:
  http:
  #pokeapi: 1.0.3
  cached_network_image: 3.3.1
  percent_indicator:
  sliding_up_panel:
  carousel_slider:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/types/
    - assets/images/variocolor/
    - assets/images/animado/
    - assets/images/animado/variocolor/
    - assets/files/
  fonts:
    - family: Elokuent_icon
      fonts:
        - asset: assets/fonts/Elokuent_icon.ttf
    - family: HankRnd-Regular
      fonts:
        - asset: assets/fonts/HankRnd_Regular.otf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
